---
title: "Fig_S1_Viz"
author: "Troy McDiarmid"
date: "2024-03-12"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

```

```{r}
##RC_Lmax visualizations

U6_Pro_combos <- read_csv("/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/FigS1_Final_Figure_Datasets/240208_U6_Pro_combos.csv")

ggplot(U6_Pro_combos, aes(x = A_BRC_Lmax)) +
  geom_histogram(adjust=1.5, fill = "black", binwidth = 1) +  
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  scale_y_continuous(breaks = c(0,4000,8000)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  xlim(0,50) +
  theme(text = element_text(family="Arial", colour = "black", size = 44)) 
  ggsave("All_U6_RC_Lmax_Dist.jpeg", width = 16, height = 3.5, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")


##Filtering for just diverse-diverse interactions

DivU6_Prom_Lmax <- U6_Pro_combos %>% 
  filter(!grepl("Syn", Name_A)) %>% 
  filter(!grepl("Syn", Name_B))  

ggplot(DivU6_Prom_Lmax, aes(x = A_BRC_Lmax)) +
  geom_histogram(adjust=1.5, fill = "#56B4E9", binwidth = 1) +  
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  scale_y_continuous(breaks = c(0,750,1500)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  xlim(0,50) +
  theme(text = element_text(family="Arial", colour = "black", size = 44)) 
  ggsave("Div_RC_Lmax_Dist.jpeg", width = 16, height = 3.5, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")


##Filtering for just synthetic-synthetic interactions

SynU6_Pro_Lmax <- U6_Pro_combos %>% 
  filter(grepl("Syn", Name_A)) %>% 
  filter(grepl("Syn", Name_B))  

ggplot(SynU6_Pro_Lmax, aes(x = A_BRC_Lmax)) +
  geom_histogram(adjust=1.5, fill = "#999999", binwidth = 1) +  
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  scale_y_continuous(breaks = c(0,1000,2000)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  xlim(0,50) +
  theme(text = element_text(family="Arial", colour = "black", size = 44)) 
  ggsave("Syn_RC_Lmax_Dist.jpeg", width = 16, height = 3.5, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
```



