---
title: "Fig_S18_Viz"
author: "Troy McDiarmid"
date: "2024-01-13"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(reshape)
library("DNABarcodes")
library("Biostrings")
library(ggridges)
```


```{r}
##Correlate new and primary edit scores 

##Read in primary HEK293T edit scores 

Normalized_Fivemer_insert_efficiency_REGEX <- read_csv("/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/FigS3_Final_Figure_Datasets/Normalized_Fivemer_insert_efficiency_REGEX.csv")

##Read in the new K562 edit data 

Five_N_pBC_rBC_iBC_Data <- read_csv("/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/FigS3_Final_Figure_Datasets/Five_N_pBC_rBC_iBC_Data.csv")

##Merge primary and new data 

Normalized_Fivemer_insert_efficiency_REGEX <- Normalized_Fivemer_insert_efficiency_REGEX %>% dplyr::rename(pBC_Seq = Plasmid_BC_Seq)

Five_N_pBC_rBC_iBC_Data_F <- Five_N_pBC_rBC_iBC_Data %>% 
  select(pBC_Seq, Mean_HEK3_Edit_Score, Mean_synHEK3_Edit_Score) %>% 
  distinct(pBC_Seq, .keep_all = TRUE)

Five_N_pBC_rBC_iBC_Data_F <- Five_N_pBC_rBC_iBC_Data_F %>% 
  left_join(Normalized_Fivemer_insert_efficiency_REGEX, by = "pBC_Seq")

##Add a column indicating if a sequence contains a 4bp Thymidine homopolymer

pBC_Counts_Parsed_Calc_Ts <- Five_N_pBC_rBC_iBC_Data_F %>% 
  filter(grepl("TTTT", pBC_Seq))  

pBC_Counts_Parsed_Calc_Ts$Four_bp_Homopolymer <- "TTTT"

pBC_Counts_Parsed_Calc_No_Homopolymers <- Five_N_pBC_rBC_iBC_Data_F %>% 
  filter(!grepl("TTTT", pBC_Seq)) 

pBC_Counts_Parsed_Calc_No_Homopolymers$Four_bp_Homopolymer <- "No_4bp_Homopolymers"

Five_N_pBC_rBC_iBC_Data_F <- rbind(pBC_Counts_Parsed_Calc_No_Homopolymers, pBC_Counts_Parsed_Calc_Ts)



##Plot and correlate new edit scores with old edit scores

ggplot(Five_N_pBC_rBC_iBC_Data_F, aes(x = log2(Mean_synHEK3_Edit_Score), y = log2(Edit_Score_5N), colour = Four_bp_Homopolymer, size = Four_bp_Homopolymer)) +
  geom_point() +
  scale_color_manual(values=c("black", "#56B4E9", "black", "#56B4E9")) +
  scale_size_manual(values=c(4, 6)) +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 39), plot.margin = margin(0, 15, 0, 20)) 
  ggsave("5N_pBCrBCiBC_Primary_HEK293T_vs_Validation_Edit_Score_Corr_K562.jpeg", width = 9, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
  
cor.test(Five_N_pBC_rBC_iBC_Data_F$Mean_synHEK3_Edit_Score, Five_N_pBC_rBC_iBC_Data_F$Edit_Score_5N)
cor.test(log2(Five_N_pBC_rBC_iBC_Data_F$Mean_synHEK3_Edit_Score), log2(Five_N_pBC_rBC_iBC_Data_F$Edit_Score_5N))
cor.test(log2(Five_N_pBC_rBC_iBC_Data_F$Mean_synHEK3_Edit_Score), log2(Five_N_pBC_rBC_iBC_Data_F$Edit_Score_5N), method = "spearman")


```



```{r}
##Correlate edit scores with transcription scores  

##Read in the new K562 edit data 

Five_N_pBC_rBC_iBC_Data <- read_csv("/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/FigS3_Final_Figure_Datasets/Five_N_pBC_rBC_iBC_Data.csv")

##Add a column indicating if a sequence contains a 4bp Thymidine homopolymer

pBC_Counts_Parsed_Calc_Ts <- Five_N_pBC_rBC_iBC_Data %>% 
  filter(grepl("TTTT", pBC_Seq))  

pBC_Counts_Parsed_Calc_Ts$Four_bp_Homopolymer <- "TTTT"

pBC_Counts_Parsed_Calc_No_Homopolymers <- Five_N_pBC_rBC_iBC_Data %>% 
  filter(!grepl("TTTT", pBC_Seq)) 

pBC_Counts_Parsed_Calc_No_Homopolymers$Four_bp_Homopolymer <- "No_4bp_Homopolymers"

Five_N_pBC_rBC_iBC_Data <- rbind(pBC_Counts_Parsed_Calc_No_Homopolymers, pBC_Counts_Parsed_Calc_Ts)



##Plot and correlate edit scores with transcription scores 

ggplot(Five_N_pBC_rBC_iBC_Data, aes(x = log2(Mean_synHEK3_Edit_Score), y = log2(Mean_Transcription_Score), colour = Four_bp_Homopolymer, size = Four_bp_Homopolymer)) +
  geom_point() +
  scale_color_manual(values=c("black", "#56B4E9", "black", "#56B4E9")) +
  scale_size_manual(values=c(4, 6)) +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 39), plot.margin = margin(0, 15, 0, 20)) 
  ggsave("5N_pBCrBCiBC_Transcription_vs_Edit_Score_Corr_K562.jpeg", width = 9, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
  

cor.test(Five_N_pBC_rBC_iBC_Data$Mean_synHEK3_Edit_Score, Pol_III_Pro_Edit_Scores$Mean_Transcription_Score)
cor.test(Five_N_pBC_rBC_iBC_Data$Mean_synHEK3_Edit_Score, Pol_III_Pro_Edit_Scores$Mean_Transcription_Score, method = "spearman")
cor.test(log2(Five_N_pBC_rBC_iBC_Data$Mean_synHEK3_Edit_Score), log2(Five_N_pBC_rBC_iBC_Data$Mean_Transcription_Score))

```


```{r}
##Plot effect of polyT sequence 

Five_N_pBC_rBC_iBC_Data_Unique <- Five_N_pBC_rBC_iBC_Data %>% 
  distinct(pBC_Seq, .keep_all = TRUE)

  
ggplot(Five_N_pBC_rBC_iBC_Data_Unique, aes(y = log2(Mean_synHEK3_Edit_Score), x = Four_bp_Homopolymer, fill = Four_bp_Homopolymer, colour = Four_bp_Homopolymer)) +
  theme_classic() +
  scale_fill_manual(values=c("black", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9")) +
  scale_colour_manual(values=c("black", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9")) +
  geom_boxplot(fill = NA, width = 0.75, lwd =1.5, outlier.shape = NA) +
  geom_jitter(size = 4, width = 0.1, height = 0) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-6, -4,-2,0,2,4)) +
  theme(axis.line = element_line(colour = 'black', size = 0.9)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.9)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 40)) +
  theme(axis.text.x = element_blank())
  ggsave("5N_pBCrBCiBC_TTTT_synHEK3_Boxplot.jpeg", width = 7, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")

  
  
ggplot(Five_N_pBC_rBC_iBC_Data_Unique, aes(y = log2(Mean_Transcription_Score), x = Four_bp_Homopolymer, fill = Four_bp_Homopolymer, colour = Four_bp_Homopolymer)) +
  theme_classic() +
  scale_fill_manual(values=c("black", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9")) +
  scale_colour_manual(values=c("black", "#56B4E9", "#56B4E9", "#56B4E9", "#56B4E9")) +
  geom_boxplot(fill = NA, width = 0.75, lwd =1.5, outlier.shape = NA) +
  geom_jitter(size = 4, width = 0.1, height = 0) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-6, -4,-2,0,2,4)) +
  theme(axis.line = element_line(colour = 'black', size = 0.9)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.9)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 40)) +
  theme(axis.text.x = element_blank())
  ggsave("5N_pBCrBCiBC_TTTT_Transcription_Boxplot.jpeg", width = 7, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
```


```{r} 
##Calculate and average replicate edit score across the 3 8N iBCs 

##Calculate correlation between replicates

Pol_III_Pro_Edit_Scores <- Five_N_pBC_rBC_iBC_Data 

Replicate_1_Edit_Scores <- Pol_III_Pro_Edit_Scores %>% 
  filter(Replicate == 1) %>% 
  select(Four_bp_Homopolymer, pBC_Seq, Replicate_1_Transcription_Score = Transcription_Score, Replicate_1_HEK3_Edit_Score = HEK3_Edit_Score, Replicate_1_synHEK3_Edit_Score = synHEK3_Edit_Score)
Replicate_2_Edit_Scores <- Pol_III_Pro_Edit_Scores %>% 
  filter(Replicate == 2) %>% 
  select(pBC_Seq, Replicate_2_Transcription_Score = Transcription_Score, Replicate_2_HEK3_Edit_Score = HEK3_Edit_Score, Replicate_2_synHEK3_Edit_Score = synHEK3_Edit_Score)
Replicate_3_Edit_Scores <- Pol_III_Pro_Edit_Scores %>% 
  filter(Replicate == 3) %>% 
  select(pBC_Seq, Replicate_3_Transcription_Score = Transcription_Score, Replicate_3_HEK3_Edit_Score = HEK3_Edit_Score, Replicate_3_synHEK3_Edit_Score = synHEK3_Edit_Score)
Replicate_4_Edit_Scores <- Pol_III_Pro_Edit_Scores %>% 
  filter(Replicate == 4) %>% 
  select(pBC_Seq, Replicate_4_Transcription_Score = Transcription_Score, Replicate_4_HEK3_Edit_Score = HEK3_Edit_Score, Replicate_4_synHEK3_Edit_Score = synHEK3_Edit_Score)

Pol_III_Pro_Edit_Scores_By_Replicate <- Replicate_1_Edit_Scores %>% 
  left_join(Replicate_2_Edit_Scores, by = "pBC_Seq")

Pol_III_Pro_Edit_Scores_By_Replicate <- Pol_III_Pro_Edit_Scores_By_Replicate %>% 
  left_join(Replicate_3_Edit_Scores, by = "pBC_Seq")

Pol_III_Pro_Edit_Scores_By_Replicate <- Pol_III_Pro_Edit_Scores_By_Replicate %>% 
  left_join(Replicate_4_Edit_Scores, by = "pBC_Seq") %>% 
  select(Four_bp_Homopolymer, pBC_Seq, Replicate_1_Transcription_Score, Replicate_2_Transcription_Score, Replicate_3_Transcription_Score, Replicate_4_Transcription_Score, Replicate_1_synHEK3_Edit_Score, Replicate_2_synHEK3_Edit_Score, Replicate_3_synHEK3_Edit_Score, Replicate_4_synHEK3_Edit_Score)

##Make an example correlation plot for editing

ggplot(Pol_III_Pro_Edit_Scores_By_Replicate, aes(x = log2(Replicate_1_synHEK3_Edit_Score), y = log2(Replicate_2_synHEK3_Edit_Score), colour = Four_bp_Homopolymer, size = Four_bp_Homopolymer)) +
  geom_point() +
  scale_color_manual(values=c("black", "#56B4E9", "black", "#56B4E9")) +
  scale_size_manual(values=c(4, 6)) +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 39), plot.margin = margin(0, 15, 0, 20)) 
  ggsave("5N_pBCrBCiBC_Rep1_Rep2_synHEK3_Edit_Corr_K562.jpeg", width = 9, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
  
cor.test(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_synHEK3_Edit_Score, Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_synHEK3_Edit_Score)
cor.test(log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_synHEK3_Edit_Score), log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_synHEK3_Edit_Score))
cor.test(log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_synHEK3_Edit_Score), log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_synHEK3_Edit_Score), method = "spearman")

##Make an example correlation plot for transcription

ggplot(Pol_III_Pro_Edit_Scores_By_Replicate, aes(x = log2(Replicate_1_Transcription_Score), y = log2(Replicate_2_Transcription_Score), colour = Four_bp_Homopolymer, size = Four_bp_Homopolymer)) +
  geom_point() +
  scale_color_manual(values=c("black", "#56B4E9", "black", "#56B4E9")) +
  scale_size_manual(values=c(4, 6)) +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), breaks = c(-8,-4,0,4)) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.8)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.8)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 39), plot.margin = margin(0, 15, 0, 20)) 
  ggsave("5N_pBCrBCiBC_Rep1_Rep2_Transcription_Corr_K562.jpeg", width = 9, height = 7, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")
  
cor.test(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_Transcription_Score, Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_Transcription_Score)
cor.test(log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_Transcription_Score), log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_Transcription_Score))
cor.test(log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_1_Transcription_Score), log2(Pol_III_Pro_Edit_Scores_By_Replicate$Replicate_2_Transcription_Score), method = "spearman")



```

```{r}
##Make a correlation matrix for edit scores 

##Select the relevant columns

Replicate_Edit_Scores_U6_Matrix <- Pol_III_Pro_Edit_Scores_By_Replicate %>% 
  select(Replicate_1_BC = Replicate_1_synHEK3_Edit_Score, Replicate_2_BC = Replicate_2_synHEK3_Edit_Score, Replicate_3_BC = Replicate_3_synHEK3_Edit_Score, Replicate_4_BC = Replicate_4_synHEK3_Edit_Score) 

##Convert to matrix and correlate

Replicate_Edit_Scores_U6_Matrix <- as.matrix(Replicate_Edit_Scores_U6_Matrix)

Replicate_Edit_Scores_U6_Corr_Matrix <- cor(Replicate_Edit_Scores_U6_Matrix, use="pairwise.complete.obs")

##Pivoting data longer for plotting

Replicate_Edit_Scores_U6_Corr_DF <- melt(Replicate_Edit_Scores_U6_Corr_Matrix) 

Replicate_Edit_Scores_U6_Corr_DF <- Replicate_Edit_Scores_U6_Corr_DF %>% 
  separate(X1, into = c("Replicate_X", "Garbage"), sep = "_N") %>% 
  separate(X2, into = c("Replicate_Y", "Garbagee"), sep = "_N") %>% 
  select(-Garbage, !Garbagee)

Replicate_Edit_Scores_U6_Corr_DF <- Replicate_Edit_Scores_U6_Corr_DF %>% 
  select(Replicate_X, Replicate_Y, Corr = value) %>% 
  mutate(Corr = round(Corr, digits = 2))


Replicate_Edit_Scores_U6_Corr_DF$Replicate_X <- ordered(Replicate_Edit_Scores_U6_Corr_DF$Replicate_X, levels = c("Replicate_1_BC", "Replicate_2_BC", "Replicate_3_BC", "Replicate_4_BC"))

Replicate_Edit_Scores_U6_Corr_DF$Replicate_Y <- ordered(Replicate_Edit_Scores_U6_Corr_DF$Replicate_Y, levels = c("Replicate_4_BC", "Replicate_3_BC", "Replicate_2_BC", "Replicate_1_BC"))

##Making correlation heatmap 


ggplot(Replicate_Edit_Scores_U6_Corr_DF, aes(x = Replicate_X, y = Replicate_Y, fill = Corr)) +
  geom_tile() +
  theme_void() +
  geom_text(aes(label = Corr), color = "white", size = 8.5) +
  scale_fill_continuous(limits=c(0.5, 1)) +
  theme(axis.ticks.length=unit(0, "cm")) +
  labs(title = "", x = "", y = "") + 
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12))
ggsave("5N_Edit_Score_Replicate_Heatmap.jpeg", width = 5.5, height = 4, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")


##Make a correlation matrix for transcription scores 

##Select the relevant columns

Replicate_Edit_Scores_U6_Matrix <- Pol_III_Pro_Edit_Scores_By_Replicate %>% 
  select(Replicate_1_BC = Replicate_1_Transcription_Score, Replicate_2_BC = Replicate_2_Transcription_Score, Replicate_3_BC = Replicate_3_Transcription_Score, Replicate_4_BC = Replicate_4_Transcription_Score) 

##Convert to matrix and correlate

Replicate_Edit_Scores_U6_Matrix <- as.matrix(Replicate_Edit_Scores_U6_Matrix)

Replicate_Edit_Scores_U6_Corr_Matrix <- cor(Replicate_Edit_Scores_U6_Matrix, use="pairwise.complete.obs")

##Pivoting data longer for plotting

Replicate_Edit_Scores_U6_Corr_DF <- melt(Replicate_Edit_Scores_U6_Corr_Matrix) 

Replicate_Edit_Scores_U6_Corr_DF <- Replicate_Edit_Scores_U6_Corr_DF %>% 
  separate(X1, into = c("Replicate_X", "Garbage"), sep = "_N") %>% 
  separate(X2, into = c("Replicate_Y", "Garbagee"), sep = "_N") %>% 
  select(-Garbage, !Garbagee)

Replicate_Edit_Scores_U6_Corr_DF <- Replicate_Edit_Scores_U6_Corr_DF %>% 
  select(Replicate_X, Replicate_Y, Corr = value) %>% 
  mutate(Corr = round(Corr, digits = 2))


Replicate_Edit_Scores_U6_Corr_DF$Replicate_X <- ordered(Replicate_Edit_Scores_U6_Corr_DF$Replicate_X, levels = c("Replicate_1_BC", "Replicate_2_BC", "Replicate_3_BC", "Replicate_4_BC"))

Replicate_Edit_Scores_U6_Corr_DF$Replicate_Y <- ordered(Replicate_Edit_Scores_U6_Corr_DF$Replicate_Y, levels = c("Replicate_4_BC", "Replicate_3_BC", "Replicate_2_BC", "Replicate_1_BC"))

##Making correlation heatmap 


ggplot(Replicate_Edit_Scores_U6_Corr_DF, aes(x = Replicate_X, y = Replicate_Y, fill = Corr)) +
  geom_tile() +
  theme_void() +
  geom_text(aes(label = Corr), color = "white", size = 8.5) +
  scale_fill_continuous(limits=c(0.5, 1)) +
  theme(axis.ticks.length=unit(0, "cm")) +
  labs(title = "", x = "", y = "") + 
  theme(axis.text = element_text(family="Arial", colour = "black", size = 12))
ggsave("5N_Transcription_Replicate_Heatmap.jpeg", width = 5.5, height = 4, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")

```



