---
title: "Fig_2_Viz"
author: "Troy McDiarmid"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

```



```{r}


##TAPE position 1 across units in the assembly 

TAPE_Position_Editing <- read_csv("/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/FigS13_Final_Figure_Datasets/10unit_Assembly_TAPE_Insertion_Count_And_Proportion_By_Position.csv")

##Plotting

TAPE_Position_1_Editing <- TAPE_Position_Editing %>% 
  filter(TAPE_Position == 1)


ggplot(TAPE_Position_1_Editing, aes(x = as.factor(Assembly_Position), y = Insertion_Proportion)) +
  geom_boxplot(colour = "black", width = 0.35, lwd = 0.4, outlier.shape = NA, fill = "#56B4E9", position = position_dodge(width=0.1)) +
  scale_shape_manual(values = c(16, 16)) +
  geom_point(colour = "black", size = 2.5) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.5)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.5)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  ylim(0,30) +
  scale_x_discrete(expand=c(0.04,0.04)) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 18))
ggsave("TAPE_Position_1_Editing.jpeg", width = 16, height = 3, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")

##Plotting

TAPE_Position_2_Editing <- TAPE_Position_Editing %>% 
  filter(TAPE_Position == 2)


ggplot(TAPE_Position_2_Editing, aes(x = as.factor(Assembly_Position), y = Insertion_Proportion)) +
  geom_boxplot(colour = "black", width = 0.35, lwd = 0.4, outlier.shape = NA, fill = "#56B4E9", position = position_dodge(width=0.1)) +
  scale_shape_manual(values = c(16, 16)) +
  geom_point(colour = "black", size = 2.5) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.5)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.5)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  ylim(0,30) +
  scale_x_discrete(expand=c(0.04,0.04)) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 18))
ggsave("TAPE_Position_2_Editing.jpeg", width = 16, height = 3, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")

##Plotting

TAPE_Position_3_Editing <- TAPE_Position_Editing %>% 
  filter(TAPE_Position == 3)


ggplot(TAPE_Position_3_Editing, aes(x = as.factor(Assembly_Position), y = Insertion_Proportion)) +
  geom_boxplot(colour = "black", width = 0.35, lwd = 0.4, outlier.shape = NA, fill = "#56B4E9", position = position_dodge(width=0.1)) +
  scale_shape_manual(values = c(16, 16)) +
  geom_point(colour = "black", size = 2.5) +
  theme_classic() +
  theme(axis.line = element_line(colour = 'black', size = 0.5)) +
  theme(axis.ticks = element_line(colour = "black", size = 0.5)) +
  theme(axis.ticks.length=unit(.2, "cm")) +
  ylim(0,30) +
  scale_x_discrete(expand=c(0.04,0.04)) +
  labs(title = "", x = "", y = "") +
  theme(legend.position = "none") +
  theme(text = element_text(family="Arial", colour = "black", size = 18))
ggsave("TAPE_Position_3_Editing.jpeg", width = 16, height = 3, path = "/Users/troymcdiarmid/Documents/U6_pro_series/Figs/Pub_Figs/")



```

